name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  ci:
    name: CI (build + test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"
          cache: true

      - name: Go env
        run: go env

      - name: Build
        working-directory: .
        run: go build -o go-notes-app

      - name: Test
        working-directory: .
        run: go test ./...

  cd:
    name: CD (deploy placeholder)
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - name: Show SSH deploy command
        run: |
          echo "Aqui seria feita a ligação por SSH:"
          echo "ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'cd /home/appuser/go-notes && ./scripts/deploy.sh'"
          echo "Na prática, o script deploy.sh é executado manualmente na VM."
